export const timezoneOptions = [
  // ── Россия (первыми, как основная аудитория) ──────────────────
  { value: 'Europe/Kaliningrad',  label: 'UTC+2  — Калининград' },
  { value: 'Europe/Moscow',       label: 'UTC+3  — Москва, Санкт-Петербург, Краснодар' },
  { value: 'Europe/Samara',       label: 'UTC+4  — Самара, Ижевск, Ульяновск' },
  { value: 'Asia/Yekaterinburg',  label: 'UTC+5  — Екатеринбург, Уфа, Челябинск' },
  { value: 'Asia/Omsk',           label: 'UTC+6  — Омск' },
  { value: 'Asia/Novosibirsk',    label: 'UTC+7  — Новосибирск, Барнаул, Томск' },
  { value: 'Asia/Krasnoyarsk',    label: 'UTC+7  — Красноярск, Кемерово, Хакасия' },
  { value: 'Asia/Irkutsk',        label: 'UTC+8  — Иркутск, Улан-Удэ' },
  { value: 'Asia/Yakutsk',        label: 'UTC+9  — Якутск, Чита, Забайкалье' },
  { value: 'Asia/Vladivostok',    label: 'UTC+10 — Владивосток, Хабаровск' },
  { value: 'Asia/Sakhalin',       label: 'UTC+11 — Сахалин' },
  { value: 'Asia/Magadan',        label: 'UTC+11 — Магадан, Среднеколымск' },
  { value: 'Asia/Kamchatka',      label: 'UTC+12 — Петропавловск-Камчатский' },
  { value: 'Asia/Anadyr',         label: 'UTC+12 — Анадырь, Чукотка' },

  // ── Мир (UTC−12 → UTC+14) ────────────────────────────────────
  { value: 'Etc/GMT+12',          label: 'UTC−12 — Линия перемены дат (запад)' },
  { value: 'Pacific/Pago_Pago',   label: 'UTC−11 — Самоа, Паго-Паго' },
  { value: 'Pacific/Honolulu',    label: 'UTC−10 — Гавайи, Гонолулу' },
  { value: 'Pacific/Marquesas',   label: 'UTC−9:30 — Маркизские острова' },
  { value: 'America/Anchorage',   label: 'UTC−9  — Аляска, Анкоридж' },
  { value: 'America/Los_Angeles', label: 'UTC−8  — Лос-Анджелес, Сиэтл, Ванкувер' },
  { value: 'America/Denver',      label: 'UTC−7  — Денвер, Финикс, Солт-Лейк-Сити' },
  { value: 'America/Chicago',     label: 'UTC−6  — Чикаго, Мехико, Виннипег' },
  { value: 'America/New_York',    label: 'UTC−5  — Нью-Йорк, Торонто, Майами' },
  { value: 'America/Halifax',     label: 'UTC−4  — Галифакс, Каракас, Ла-Пас' },
  { value: 'America/St_Johns',    label: 'UTC−3:30 — Ньюфаундленд' },
  { value: 'America/Sao_Paulo',   label: 'UTC−3  — Сан-Паулу, Буэнос-Айрес, Монтевидео' },
  { value: 'America/Noronha',     label: 'UTC−2  — Фернанду-ди-Норонья' },
  { value: 'Atlantic/Azores',     label: 'UTC−1  — Азорские острова' },
  { value: 'UTC',                 label: 'UTC+0  — Лондон, Дублин, Лиссабон, Рейкьявик' },
  { value: 'Europe/Paris',        label: 'UTC+1  — Берлин, Париж, Рим, Варшава, Мадрид' },
  { value: 'Europe/Helsinki',     label: 'UTC+2  — Хельсинки, Киев, Афины, Каир' },
  { value: 'Asia/Tehran',         label: 'UTC+3:30 — Тегеран, Иран' },
  { value: 'Asia/Dubai',          label: 'UTC+4  — Дубай, Абу-Даби, Баку, Тбилиси' },
  { value: 'Asia/Kabul',          label: 'UTC+4:30 — Кабул, Афганистан' },
  { value: 'Asia/Karachi',        label: 'UTC+5  — Карачи, Ташкент, Исламабад' },
  { value: 'Asia/Kolkata',        label: 'UTC+5:30 — Мумбаи, Нью-Дели, Индия' },
  { value: 'Asia/Kathmandu',      label: 'UTC+5:45 — Катманду, Непал' },
  { value: 'Asia/Dhaka',          label: 'UTC+6  — Дакка, Алматы, Астана' },
  { value: 'Asia/Yangon',         label: 'UTC+6:30 — Янгон, Мьянма' },
  { value: 'Asia/Bangkok',        label: 'UTC+7  — Бангкок, Джакарта, Ханой' },
  { value: 'Asia/Shanghai',       label: 'UTC+8  — Пекин, Сингапур, Гонконг, Куала-Лумпур' },
  { value: 'Australia/Eucla',     label: 'UTC+8:45 — Юкла, Западная Австралия' },
  { value: 'Asia/Tokyo',          label: 'UTC+9  — Токио, Сеул, Пхеньян' },
  { value: 'Australia/Darwin',    label: 'UTC+9:30 — Дарвин, Северная территория' },
  { value: 'Australia/Sydney',    label: 'UTC+10 — Сидней, Мельбурн, Брисбен' },
  { value: 'Australia/Lord_Howe', label: 'UTC+10:30 — Остров Лорд-Хау' },
  { value: 'Pacific/Guadalcanal', label: 'UTC+11 — Хониара, Соломоновы острова' },
  { value: 'Pacific/Auckland',    label: 'UTC+12 — Окленд, Веллингтон, Фиджи' },
  { value: 'Pacific/Chatham',     label: 'UTC+12:45 — Острова Чатем (Новая Зеландия)' },
  { value: 'Pacific/Tongatapu',   label: 'UTC+13 — Нукуалофа, Тонга, Самоа' },
  { value: 'Pacific/Kiritimati',  label: 'UTC+14 — Острова Лайн, Кирибати' },
]
