export const timezoneOptions = [
  // Россия
  { value: 'Europe/Kaliningrad',  label: 'UTC+2  — Калининград' },
  { value: 'Europe/Moscow',       label: 'UTC+3  — Москва, Санкт-Петербург' },
  { value: 'Europe/Samara',       label: 'UTC+4  — Самара, Ижевск, Ульяновск' },
  { value: 'Asia/Yekaterinburg',  label: 'UTC+5  — Екатеринбург, Уфа, Челябинск' },
  { value: 'Asia/Omsk',           label: 'UTC+6  — Омск' },
  { value: 'Asia/Novosibirsk',    label: 'UTC+7  — Новосибирск, Барнаул, Томск' },
  { value: 'Asia/Krasnoyarsk',    label: 'UTC+7  — Красноярск, Хакасия' },
  { value: 'Asia/Irkutsk',        label: 'UTC+8  — Иркутск, Улан-Удэ, Бурятия' },
  { value: 'Asia/Yakutsk',        label: 'UTC+9  — Якутск, Чита, Забайкалье' },
  { value: 'Asia/Vladivostok',    label: 'UTC+10 — Владивосток, Хабаровск' },
  { value: 'Asia/Magadan',        label: 'UTC+11 — Магадан, Сахалин' },
  { value: 'Asia/Kamchatka',      label: 'UTC+12 — Петропавловск-Камчатский, Чукотка' },
  // Мировые
  { value: 'Etc/GMT+12',          label: 'UTC−12' },
  { value: 'Pacific/Honolulu',    label: 'UTC−10 — Гонолулу' },
  { value: 'America/Anchorage',   label: 'UTC−9  — Аляска' },
  { value: 'America/Los_Angeles', label: 'UTC−8  — Лос-Анджелес' },
  { value: 'America/Denver',      label: 'UTC−7  — Денвер' },
  { value: 'America/Chicago',     label: 'UTC−6  — Чикаго, Мехико' },
  { value: 'America/New_York',    label: 'UTC−5  — Нью-Йорк, Торонто' },
  { value: 'America/Sao_Paulo',   label: 'UTC−3  — Сан-Паулу, Буэнос-Айрес' },
  { value: 'UTC',                 label: 'UTC+0  — Лондон, Дублин' },
  { value: 'Europe/Paris',        label: 'UTC+1  — Берлин, Париж, Рим' },
  { value: 'Europe/Helsinki',     label: 'UTC+2  — Хельсинки, Киев, Каир' },
  { value: 'Asia/Dubai',          label: 'UTC+4  — Дубай, Баку, Тбилиси' },
  { value: 'Asia/Karachi',        label: 'UTC+5  — Карачи, Ташкент' },
  { value: 'Asia/Kolkata',        label: 'UTC+5:30 — Индия' },
  { value: 'Asia/Dhaka',          label: 'UTC+6  — Дакка, Алматы, Астана' },
  { value: 'Asia/Bangkok',        label: 'UTC+7  — Бангкок, Джакарта' },
  { value: 'Asia/Shanghai',       label: 'UTC+8  — Пекин, Сингапур, Гонконг' },
  { value: 'Asia/Tokyo',          label: 'UTC+9  — Токио, Сеул' },
  { value: 'Australia/Sydney',    label: 'UTC+10 — Сидней, Мельбурн' },
  { value: 'Pacific/Auckland',    label: 'UTC+12 — Окленд, Фиджи' },
]
